[theme]
base = "dark"
# backgroundColor = "#DCD0A8"
baseFontSize = 20
showWidgetBorder = true
showSidebarBorder = true

[theme.sidebar]
# Primary accent color.
backgroundColor = "#004030"
textColor = "#FFF9E5"
borderColor = "#FFF9E5"